name: fiumaping
services:
  back:
    container_name: back
    image: back:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24